name: upgrade
inputs:
  application:
    required: true
  repository:
    required: true
  branch:
     required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - name: List all directories
      run: |
        ls -al
      shell: bash
