on: [push, pull_request]
name: upgrade
jobs:
  upgrade:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['omp','ojs','ops']
        database: ['pgsql','mysql']
        php-version: [ '8.1' ,'8.2']
      
    name: upgrade
    steps:
      - uses: xmlFlow/upgrade-action@v1
        with:
          application:  ${{matrix.application}}
          repository: 'pkp'
          branch: 'main'
